sensors:
- sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  image_topic: /camera2/depth/image_raw
  queue_size: 5
  near_clipping_plane_distance: 0.3
  far_clipping_plane_distance: 5.0
  shadow_threshold: 0.2
  padding_scale: 4.0
  padding_offset: 0.03
  shape_padding: 0.01
  shape_scale: 1.0
  filtered_cloud_topic: filtered_cloud2

- sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  image_topic: /camera1/depth/image_raw
  queue_size: 5
  near_clipping_plane_distance: 0.3
  far_clipping_plane_distance: 5.0
  skip_vertical_pixels: 1
  skip_horizontal_pixels: 1
  shadow_threshold: 0.2
  padding_scale: 4.0
  padding_offset: 0.03
  filtered_cloud_topic: filtered_cloud1

# - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
#   image_topic: /camera/depth/image_raw
#   queue_size: 5
#   near_clipping_plane_distance: 0.3
#   far_clipping_plane_distance: 5.0
#   skip_vertical_pixels: 1
#   skip_horizontal_pixels: 1
#   shadow_threshold: 0.2
#   padding_scale: 4.0
#   padding_offset: 0.03
#   filtered_cloud_topic: filtered_cloud1